# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{macruby-asl-logger}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eloy Duran"]
  s.date = %q{2010-05-21}
  s.description = %q{A MacRuby wrapper of the Apple System Log facility}
  s.email = %q{eloy.de.enige@gmail.com}
  s.extensions = ["ext/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    "README",
     "Rakefile",
     "ext/extconf.rb",
     "ext/logger.c",
     "spec/add_spec.rb",
     "spec/close_spec.rb",
     "spec/debug_spec.rb",
     "spec/new_spec.rb",
     "spec/severity_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/alloy/macruby-asl-logger}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.required_ruby_version = Gem::Requirement.new("~> 1.9")
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A MacRuby wrapper of the Apple System Log facility}
  s.test_files = [
    "spec/add_spec.rb",
     "spec/close_spec.rb",
     "spec/debug_spec.rb",
     "spec/new_spec.rb",
     "spec/severity_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

